language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t andreiovidiurosu/docker-react -f Dockerfile.dev .

script:
  - docker run andreiovidiurosu/docker-react npm run test -- --coverage
